//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export namespace Enums {
	export enum UserRole {
		User = 1,
		Admin = 2
	}
	export enum ExerciseGroupType {
		Straight = 1,
		Superset = 2,
		Circuit = 3
	}
	export enum ExerciseSetType {
		Warmup = 1,
		Working = 2,
		Dropset = 3,
		Failure = 4
	}
	export enum PersonalRecordType {
		OneRepMax = 1,
		MaxWeight = 2,
		MaxReps = 3,
		MaxVolume = 4
	}
}
export namespace JsonModels.WorkoutTemplates {
	export interface CreateTemplateFromWorkoutRequest
	{
		name?: string;
		description?: string;
		estimatedDurationMinutes?: number;
		isPublic: boolean;
	}
	export interface CreateWorkoutTemplateExerciseRequest
	{
		groupType: Enums.ExerciseGroupType;
		clientGroupId?: number;
		exerciseId: number;
		notes?: string;
		sets: JsonModels.WorkoutTemplates.CreateWorkoutTemplateExerciseSetRequest[];
	}
	export interface CreateWorkoutTemplateExerciseSetRequest
	{
		setType: Enums.ExerciseSetType;
		weightKg?: number;
		reps?: number;
		durationSeconds?: number;
		distanceMeters?: number;
		rpe?: number;
		restSeconds?: number;
		notes?: string;
	}
	export interface CreateWorkoutTemplateRequest
	{
		name: string;
		description?: string;
		estimatedDurationMinutes?: number;
		isPublic: boolean;
		exercises: JsonModels.WorkoutTemplates.CreateWorkoutTemplateExerciseRequest[];
	}
	export interface WorkoutTemplateExerciseGroupModel
	{
		id: number;
		sortOrder: number;
		groupType: Enums.ExerciseGroupType;
		restBetweenExercisesSeconds?: number;
		restAfterGroupSeconds?: number;
		rounds: number;
		exercises: JsonModels.WorkoutTemplates.WorkoutTemplateExerciseModel[];
	}
	export interface WorkoutTemplateExerciseModel
	{
		id: number;
		exerciseId: number;
		exerciseName: string;
		exerciseImageUrl?: string;
		orderIndex: number;
		targetSets: number;
		targetReps?: string;
		targetWeightKg?: number;
		targetRestSeconds?: number;
		tempo?: string;
		notes?: string;
		sets: JsonModels.WorkoutTemplates.WorkoutTemplateExerciseSetModel[];
	}
	export interface WorkoutTemplateExerciseSetModel
	{
		id: number;
		orderIndex: number;
		setType: Enums.ExerciseSetType;
		weightKg?: number;
		reps?: number;
		durationSeconds?: number;
		distanceMeters?: number;
		rpe?: number;
		restSeconds?: number;
		notes?: string;
	}
	export interface WorkoutTemplateModel
	{
		id: number;
		userId?: number;
		name: string;
		description?: string;
		estimatedDurationMinutes?: number;
		isPublic: boolean;
		exerciseCount: number;
		setCount: number;
		dateCreated: string;
		groups: JsonModels.WorkoutTemplates.WorkoutTemplateExerciseGroupModel[];
	}
}
export namespace JsonModels.Workouts {
	export interface CreateWorkoutExerciseRequest
	{
		groupType: Enums.ExerciseGroupType;
		clientGroupId?: number;
		orderIndex: number;
		exerciseId: number;
		notes?: string;
		sets: JsonModels.Workouts.CreateWorkoutSetRequest[];
	}
	export interface CreateWorkoutSetRequest
	{
		setType: Enums.ExerciseSetType;
		isCompleted: boolean;
		weightKg?: number;
		reps?: number;
		durationSeconds?: number;
		distanceMeters?: number;
		rpe?: number;
		notes?: string;
	}
	export interface PreviousExerciseSetModel
	{
		setNumber: number;
		setType: Enums.ExerciseSetType;
		weightKg?: number;
		reps?: number;
		durationSeconds?: number;
		distanceMeters?: number;
		rpe?: number;
		notes?: string;
	}
	export interface PreviousExerciseSetsModel
	{
		exerciseId: number;
		exerciseName: string;
		workoutId: number;
		workoutTitle: string;
		workoutStartedAt: string;
		sets: JsonModels.Workouts.PreviousExerciseSetModel[];
	}
	export interface PreviousExerciseSetsQueryRequest
	{
		exerciseIds: number[];
	}
	export interface PreviousExerciseSetsResponse
	{
		items: JsonModels.Workouts.PreviousExerciseSetsModel[];
	}
	export interface SaveWorkoutRequest
	{
		workoutId?: number;
		workoutTemplateId?: number;
		title: string;
		startedAt?: string;
		finishedAt?: string;
		notes?: string;
		exercises: JsonModels.Workouts.CreateWorkoutExerciseRequest[];
	}
	export interface WorkoutCalendarDayModel
	{
		workoutId: number;
		title: string;
		date: string;
		durationSeconds?: number;
		totalVolumeKg?: number;
		exerciseCount: number;
		setCount: number;
	}
	export interface WorkoutCalendarQueryRequest
	{
		year: number;
		month: number;
	}
	export interface WorkoutCreatedModel
	{
		workoutId: number;
		title: string;
		startedAt?: string;
		finishedAt?: string;
		exerciseCount: number;
		setCount: number;
		totalVolumeKg?: number;
	}
	export interface WorkoutExerciseGroupModel
	{
		id: number;
		sortOrder: number;
		groupType: Enums.ExerciseGroupType;
		exercises: JsonModels.Workouts.WorkoutExerciseModel[];
	}
	export interface WorkoutExerciseModel
	{
		id: number;
		exerciseId: number;
		exerciseName: string;
		exerciseImageUrl?: string;
		orderIndex: number;
		notes?: string;
		sets: JsonModels.Workouts.WorkoutSetModel[];
	}
	export interface WorkoutModel
	{
		id: number;
		workoutTemplateId?: number;
		templateName?: string;
		title: string;
		startedAt?: string;
		finishedAt?: string;
		durationSeconds?: number;
		totalVolumeKg?: number;
		notes?: string;
		exerciseCount: number;
		setCount: number;
		groups: JsonModels.Workouts.WorkoutExerciseGroupModel[];
	}
	export interface WorkoutSetModel
	{
		id: number;
		orderIndex: number;
		setType: Enums.ExerciseSetType;
		weightKg?: number;
		reps?: number;
		durationSeconds?: number;
		distanceMeters?: number;
		rpe?: number;
		isCompleted: boolean;
		notes?: string;
	}
}
export namespace JsonModels.Users {
	export interface AdminUserModel
	{
		id: number;
		email: string;
		firstName?: string;
		lastName?: string;
		isActive: boolean;
		isAdmin: boolean;
		dateCreated: string;
		lastLoginAt?: string;
	}
	export interface UpdateUserRequest
	{
		isAdmin: boolean;
		isActive: boolean;
	}
	export interface UserQueryRequest extends JsonModels.Common.PagedRequest
	{
		search?: string;
	}
}
export namespace JsonModels.MuscleGroups {
	export interface CreateMuscleGroupRequest
	{
		name: string;
		imageUrl?: string;
	}
	export interface MuscleGroupModel
	{
		id: number;
		name: string;
		imageUrl?: string;
	}
	export interface MuscleGroupQueryRequest extends JsonModels.Common.PagedRequest
	{
		search?: string;
	}
}
export namespace JsonModels.Exercises {
	export interface ConfirmImageUploadRequest
	{
		blobName: string;
	}
	export interface CreateExerciseRequest
	{
		name: string;
		slug: string;
		description?: string;
		imageUrl?: string;
		videoUrl?: string;
		primaryMuscleGroupId: number;
		secondaryMuscleGroupId?: number;
		isPublic: boolean;
	}
	export interface ExerciseLookupModel
	{
		id: number;
		userId?: number;
		isGlobal: boolean;
		isPublic: boolean;
		name: string;
		slug: string;
		description?: string;
		imageUrl?: string;
		videoUrl?: string;
		primaryMuscleGroupId: number;
		primaryMuscleGroupName: string;
		secondaryMuscleGroupId?: number;
		secondaryMuscleGroupName?: string;
		creatorUserId?: number;
		creatorDisplayName?: string;
		dateCreated: string;
	}
	export interface ExerciseLookupRequest extends JsonModels.Common.OffsetPagedRequest
	{
		search?: string;
		muscleGroupIds?: number[];
	}
	export interface ExerciseModel
	{
		id: number;
		userId?: number;
		isPublic: boolean;
		name: string;
		slug: string;
		description?: string;
		imageUrl?: string;
		videoUrl?: string;
		primaryMuscleGroupId: number;
		secondaryMuscleGroupId?: number;
		creatorDisplayName?: string;
		dateCreated: string;
		dateModified?: string;
	}
	export interface ExerciseQueryRequest extends JsonModels.Common.PagedRequest
	{
		search?: string;
		isGlobal?: boolean;
		userId?: number;
	}
	export interface ImageUploadTicketModel
	{
		uploadUrl: string;
		blobName: string;
	}
	export interface ImageUploadTicketRequest
	{
		fileName: string;
		contentType: string;
	}
}
export namespace JsonModels.Errors {
	export interface ErrorModel
	{
		id: number;
		source?: string;
		action?: string;
		requestUrl: string;
		userAgent?: string;
		message: string;
		exception?: string;
		dateCreated: string;
		createdById?: number;
		createdByEmail?: string;
	}
	export interface ErrorQueryRequest extends JsonModels.Common.PagedRequest
	{
		search?: string;
	}
}
export namespace JsonModels.Common {
	export interface OffsetPagedRequest
	{
		skip: number;
		take: number;
	}
	export interface PagedRequest
	{
		page: number;
		pageSize: number;
	}
	export interface PagedResponse<T>
	{
		items: T[];
		totalCount: number;
		page: number;
		pageSize: number;
	}
}
export namespace JsonModels.BodyMetrics {
	export interface BodyMetricEntryModel
	{
		id: number;
		bodyWeightKg?: number;
		bodyFatPercentage?: number;
		notes?: string;
		loggedAt: string;
	}
	export interface LogBodyMetricRequest
	{
		bodyWeightKg: number;
		bodyFatPercentage?: number;
		notes?: string;
	}
}
export namespace JsonModels.Auth {
	export interface AuthResponse
	{
		success: boolean;
		message?: string;
		user?: JsonModels.Auth.UserModel;
	}
	export interface ChangePasswordRequest
	{
		currentPassword: string;
		newPassword: string;
	}
	export interface ForgotPasswordRequest
	{
		email: string;
	}
	export interface GoogleLoginRequest
	{
		credential: string;
	}
	export interface LoginRequest
	{
		email: string;
		password: string;
	}
	export interface RegisterRequest
	{
		email: string;
		password: string;
		firstName: string;
		lastName: string;
	}
	export interface ResetPasswordRequest
	{
		email: string;
		token: string;
		newPassword: string;
	}
	export interface UpdateProfileRequest
	{
		firstName: string;
		lastName?: string;
	}
	export interface UserModel
	{
		id: number;
		email: string;
		firstName?: string;
		lastName?: string;
		roles: Enums.UserRole[];
	}
}
export namespace JsonModels.Analytics {
	export interface AnalyticsOverviewModel
	{
		workoutCount: number;
		totalVolumeKg: number;
		totalSets: number;
		totalReps: number;
		volumeTrend: JsonModels.Analytics.VolumeTrendPointModel[];
		muscleGroupVolumes: JsonModels.Analytics.MuscleGroupVolumeModel[];
		personalRecords: JsonModels.Analytics.PersonalRecordSummaryModel[];
	}
	export interface AnalyticsQueryRequest
	{
		from?: string;
		to?: string;
	}
	export interface ExerciseProgressionModel
	{
		exerciseId: number;
		exerciseName: string;
		points: JsonModels.Analytics.ExerciseProgressionPointModel[];
	}
	export interface ExerciseProgressionPointModel
	{
		date: string;
		bestWeightKg?: number;
		bestReps?: number;
		estimatedOneRepMax?: number;
		totalVolumeKg: number;
	}
	export interface MuscleGroupVolumeModel
	{
		muscleGroupId: number;
		muscleGroupName: string;
		totalVolumeKg: number;
		setCount: number;
	}
	export interface PersonalRecordSummaryModel
	{
		exerciseId: number;
		exerciseName: string;
		primaryMuscleGroupId: number;
		primaryMuscleGroupName: string;
		bestWeightKg?: number;
		bestReps?: number;
		bestEstimatedOneRepMax?: number;
		bestVolumeKg?: number;
		lastTrainedOn: string;
	}
	export interface VolumeTrendPointModel
	{
		periodStart: string;
		totalVolumeKg: number;
		workoutCount: number;
	}
}
export interface JsonData<T>
{
	success: boolean;
	data?: T;
	error?: string;
	warning?: string;
}
