//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export namespace Enums {
	export enum UserRole {
		User = 1,
		Admin = 2
	}
	export enum ExerciseGroupType {
		Straight = 1,
		Superset = 2,
		Circuit = 3
	}
	export enum ExerciseSetType {
		Warmup = 1,
		Working = 2,
		Dropset = 3,
		Failure = 4
	}
	export enum EntitlementSource {
		FreePlan = 1,
		Subscription = 2,
		AdminOverride = 3
	}
	export enum TrainingGoal {
		GeneralFitness = 1,
		Hypertrophy = 2,
		Strength = 3,
		FatLoss = 4,
		Endurance = 5,
		Maintenance = 6
	}
	export enum TrainingExperienceLevel {
		Beginner = 1,
		Intermediate = 2,
		Advanced = 3
	}
	export enum WeightUnit {
		Kg = 1,
		Lb = 2
	}
	export enum DayOfWeek {
		Sunday = 0,
		Monday = 1,
		Tuesday = 2,
		Wednesday = 3,
		Thursday = 4,
		Friday = 5,
		Saturday = 6
	}
	export enum SubscriptionStatus {
		Trialing = 1,
		Active = 2,
		PastDue = 3,
		Cancelled = 4,
		Unpaid = 5,
		Incomplete = 6,
		IncompleteExpired = 7,
		Paused = 8
	}
	export enum SubscriptionFeature {
		AIChat = 1,
		AIWorkoutGeneration = 2,
		AIProgramGeneration = 3,
		AIExerciseRecognition = 4,
		AIImageGeneration = 5,
		AITrainingAnalysis = 6,
		ActiveProgramPlans = 20,
		ProgramPlanDurationMonths = 21,
		CustomWorkoutTemplates = 22,
		ExerciseHistoryMonths = 23,
		AIContextTokens = 24,
		AIConversationMessages = 25
	}
	export enum BillingInterval {
		Monthly = 1,
		Yearly = 2
	}
	export enum UsageReservationStatus {
		Active = 1,
		Committed = 2,
		Released = 3,
		Expired = 4
	}
	export enum ProgramPlanDayType {
		Workout = 1,
		Rest = 2,
		OptionalWorkout = 3,
		Recovery = 4,
		Deload = 5
	}
	export enum ProgramPlanDayStatus {
		Scheduled = 1,
		Started = 2,
		Completed = 3,
		Skipped = 4,
		Missed = 5,
		Rescheduled = 6,
		Cancelled = 7
	}
	export enum ProgramPlanStatus {
		Draft = 1,
		Active = 2,
		Paused = 3,
		Completed = 4,
		Cancelled = 5
	}
	export enum ProgramScheduleType {
		FixedWeekdays = 1,
		Rotation = 2,
		CustomCalendar = 3
	}
	export enum ExerciseEquipment {
		Barbell = 1,
		Dumbbell = 2,
		Kettlebell = 3,
		Cable = 4,
		Machine = 5,
		Bodyweight = 6,
		ResistanceBand = 7,
		MedicineBall = 8,
		Other = 9
	}
	export enum ExerciseMovementPattern {
		HorizontalPush = 1,
		HorizontalPull = 2,
		VerticalPush = 3,
		VerticalPull = 4,
		Squat = 5,
		Hinge = 6,
		Lunge = 7,
		Carry = 8,
		Rotation = 9,
		Isolation = 10,
		Other = 11
	}
	export enum ExerciseDifficulty {
		Beginner = 1,
		Intermediate = 2,
		Advanced = 3
	}
	export enum ExerciseCategory {
		Strength = 1,
		Cardio = 2,
		Mobility = 3,
		Plyometric = 4,
		Olympic = 5,
		Other = 6
	}
	export enum AIConversationStatus {
		Active = 1,
		Archived = 2,
		Deleted = 3
	}
	export enum AIMessageRole {
		User = 1,
		Assistant = 2,
		ToolCall = 3,
		ToolResult = 4,
		System = 5
	}
	export enum AIActionType {
		CreatePersonalExercise = 1,
		CreateGlobalExercise = 2,
		CreateWorkout = 3,
		CreateWorkoutTemplate = 4,
		CreateProgramPlan = 5,
		UpdateProgramPlan = 6,
		GenerateExerciseImage = 7
	}
	export enum AIActionStatus {
		PendingConfirmation = 1,
		Confirmed = 2,
		Executing = 3,
		Executed = 4,
		Rejected = 5,
		Expired = 6,
		Failed = 7
	}
	export enum AIRunStatus {
		Running = 1,
		Completed = 2,
		Failed = 3,
		Cancelled = 4,
		LimitExceeded = 5
	}
	export enum AIToolExecutionStatus {
		Running = 1,
		Completed = 2,
		Failed = 3,
		Rejected = 4
	}
	export enum UnsupportedRequestStatus {
		New = 1,
		Reviewed = 2,
		Planned = 3,
		Implemented = 4,
		Rejected = 5
	}
	export enum PersonalRecordType {
		OneRepMax = 1,
		MaxWeight = 2,
		MaxReps = 3,
		MaxVolume = 4
	}
	export enum AIModelTier {
		Fast = 1,
		Default = 2,
		Reasoning = 3
	}
	export enum UsageEntryType {
		Reservation = 1,
		Commit = 2,
		Release = 3,
		ManualAdjustment = 4,
		Refund = 5
	}
}
export namespace JsonModels.WorkoutTemplates {
	export interface CreateTemplateFromWorkoutRequest
	{
		name?: string;
		description?: string;
		estimatedDurationMinutes?: number;
		isPublic: boolean;
	}
	export interface CreateWorkoutTemplateExerciseRequest
	{
		groupType: Enums.ExerciseGroupType;
		clientGroupId?: number;
		exerciseId: number;
		notes?: string;
		sets: JsonModels.WorkoutTemplates.CreateWorkoutTemplateExerciseSetRequest[];
	}
	export interface CreateWorkoutTemplateExerciseSetRequest
	{
		setType: Enums.ExerciseSetType;
		weightKg?: number;
		reps?: number;
		durationSeconds?: number;
		distanceMeters?: number;
		rpe?: number;
		restSeconds?: number;
		notes?: string;
	}
	export interface CreateWorkoutTemplateRequest
	{
		name: string;
		description?: string;
		estimatedDurationMinutes?: number;
		isPublic: boolean;
		exercises: JsonModels.WorkoutTemplates.CreateWorkoutTemplateExerciseRequest[];
	}
	export interface WorkoutTemplateExerciseGroupModel
	{
		id: number;
		sortOrder: number;
		groupType: Enums.ExerciseGroupType;
		restBetweenExercisesSeconds?: number;
		restAfterGroupSeconds?: number;
		rounds: number;
		exercises: JsonModels.WorkoutTemplates.WorkoutTemplateExerciseModel[];
	}
	export interface WorkoutTemplateExerciseModel
	{
		id: number;
		exerciseId: number;
		exerciseName: string;
		exerciseImageUrl?: string;
		orderIndex: number;
		targetSets: number;
		targetReps?: string;
		targetWeightKg?: number;
		targetRestSeconds?: number;
		tempo?: string;
		notes?: string;
		sets: JsonModels.WorkoutTemplates.WorkoutTemplateExerciseSetModel[];
	}
	export interface WorkoutTemplateExerciseSetModel
	{
		id: number;
		orderIndex: number;
		setType: Enums.ExerciseSetType;
		weightKg?: number;
		reps?: number;
		durationSeconds?: number;
		distanceMeters?: number;
		rpe?: number;
		restSeconds?: number;
		notes?: string;
	}
	export interface WorkoutTemplateModel
	{
		id: number;
		userId?: number;
		name: string;
		description?: string;
		estimatedDurationMinutes?: number;
		isPublic: boolean;
		exerciseCount: number;
		setCount: number;
		dateCreated: string;
		groups: JsonModels.WorkoutTemplates.WorkoutTemplateExerciseGroupModel[];
	}
}
export namespace JsonModels.Workouts {
	export interface CreateWorkoutExerciseRequest
	{
		groupType: Enums.ExerciseGroupType;
		clientGroupId?: number;
		orderIndex: number;
		exerciseId: number;
		notes?: string;
		sets: JsonModels.Workouts.CreateWorkoutSetRequest[];
	}
	export interface CreateWorkoutSetRequest
	{
		setType: Enums.ExerciseSetType;
		isCompleted: boolean;
		weightKg?: number;
		reps?: number;
		durationSeconds?: number;
		distanceMeters?: number;
		rpe?: number;
		notes?: string;
	}
	export interface ExerciseHistoryModel
	{
		exerciseId: number;
		exerciseName: string;
		sessions: JsonModels.Workouts.ExerciseHistorySessionModel[];
	}
	export interface ExerciseHistoryQueryRequest
	{
		exerciseIds: number[];
		take: number;
	}
	export interface ExerciseHistoryResponse
	{
		items: JsonModels.Workouts.ExerciseHistoryModel[];
	}
	export interface ExerciseHistorySessionModel
	{
		workoutId: number;
		workoutTitle: string;
		workoutStartedAt: string;
		sets: JsonModels.Workouts.PreviousExerciseSetModel[];
	}
	export interface PreviousExerciseSetModel
	{
		setNumber: number;
		setType: Enums.ExerciseSetType;
		weightKg?: number;
		reps?: number;
		durationSeconds?: number;
		distanceMeters?: number;
		rpe?: number;
		notes?: string;
	}
	export interface PreviousExerciseSetsModel
	{
		exerciseId: number;
		exerciseName: string;
		workoutId: number;
		workoutTitle: string;
		workoutStartedAt: string;
		sets: JsonModels.Workouts.PreviousExerciseSetModel[];
	}
	export interface PreviousExerciseSetsQueryRequest
	{
		exerciseIds: number[];
	}
	export interface PreviousExerciseSetsResponse
	{
		items: JsonModels.Workouts.PreviousExerciseSetsModel[];
	}
	export interface SaveWorkoutRequest
	{
		workoutId?: number;
		workoutTemplateId?: number;
		title: string;
		startedAt?: string;
		finishedAt?: string;
		notes?: string;
		exercises: JsonModels.Workouts.CreateWorkoutExerciseRequest[];
	}
	export interface WorkoutCalendarDayModel
	{
		workoutId: number;
		title: string;
		date: string;
		durationSeconds?: number;
		totalVolumeKg?: number;
		exerciseCount: number;
		setCount: number;
	}
	export interface WorkoutCalendarQueryRequest
	{
		year: number;
		month: number;
	}
	export interface WorkoutCreatedModel
	{
		workoutId: number;
		title: string;
		startedAt?: string;
		finishedAt?: string;
		exerciseCount: number;
		setCount: number;
		totalVolumeKg?: number;
	}
	export interface WorkoutExerciseGroupModel
	{
		id: number;
		sortOrder: number;
		groupType: Enums.ExerciseGroupType;
		exercises: JsonModels.Workouts.WorkoutExerciseModel[];
	}
	export interface WorkoutExerciseModel
	{
		id: number;
		exerciseId: number;
		exerciseName: string;
		exerciseImageUrl?: string;
		orderIndex: number;
		notes?: string;
		sets: JsonModels.Workouts.WorkoutSetModel[];
	}
	export interface WorkoutModel
	{
		id: number;
		workoutTemplateId?: number;
		templateName?: string;
		title: string;
		startedAt?: string;
		finishedAt?: string;
		durationSeconds?: number;
		totalVolumeKg?: number;
		notes?: string;
		exerciseCount: number;
		setCount: number;
		groups: JsonModels.Workouts.WorkoutExerciseGroupModel[];
	}
	export interface WorkoutSetModel
	{
		id: number;
		orderIndex: number;
		setType: Enums.ExerciseSetType;
		weightKg?: number;
		reps?: number;
		durationSeconds?: number;
		distanceMeters?: number;
		rpe?: number;
		isCompleted: boolean;
		notes?: string;
	}
}
export namespace JsonModels.Users {
	export interface AdminUserModel
	{
		id: number;
		email: string;
		firstName?: string;
		lastName?: string;
		isActive: boolean;
		isAdmin: boolean;
		dateCreated: string;
		lastLoginAt?: string;
		effectivePlanCode: string;
		effectivePlanName: string;
		source: Enums.EntitlementSource;
		hasActiveOverride: boolean;
	}
	export interface UpdateUserRequest
	{
		isAdmin: boolean;
		isActive: boolean;
	}
	export interface UserQueryRequest extends JsonModels.Common.PagedRequest
	{
		search?: string;
	}
}
export namespace JsonModels.TrainingProfiles {
	export interface SaveTrainingProfileRequest
	{
		goal: Enums.TrainingGoal;
		experienceLevel: Enums.TrainingExperienceLevel;
		preferredTrainingDaysPerWeek: number;
		preferredWorkoutDurationMinutes?: number;
		weightUnit: Enums.WeightUnit;
		availableEquipment: string[];
		preferredTrainingDays: Enums.DayOfWeek[];
		exerciseRestrictions?: string;
		additionalPreferences?: string;
		allowAIPersonalization: boolean;
	}
	export interface TrainingProfileModel
	{
		goal: Enums.TrainingGoal;
		experienceLevel: Enums.TrainingExperienceLevel;
		preferredTrainingDaysPerWeek: number;
		preferredWorkoutDurationMinutes?: number;
		weightUnit: Enums.WeightUnit;
		availableEquipment: string[];
		preferredTrainingDays: Enums.DayOfWeek[];
		exerciseRestrictions?: string;
		additionalPreferences?: string;
		allowAIPersonalization: boolean;
		updatedAt: string;
	}
}
export namespace JsonModels.Subscriptions {
	export interface CurrentSubscriptionModel
	{
		planId: number;
		planCode: string;
		planName: string;
		source: Enums.EntitlementSource;
		status?: Enums.SubscriptionStatus;
		currentPeriodEnd?: string;
		cancelAtPeriodEnd: boolean;
		features: JsonModels.Subscriptions.FeatureAvailabilityModel[];
	}
	export interface EffectiveEntitlementsModel
	{
		planId: number;
		planCode: string;
		planName: string;
		source: Enums.EntitlementSource;
		features: JsonModels.Subscriptions.FeatureAvailabilityModel[];
	}
	export interface FeatureAvailabilityModel
	{
		feature: Enums.SubscriptionFeature;
		isEnabled: boolean;
		limit?: number;
		used: number;
		reserved: number;
		remaining?: number;
		resetsAt?: string;
	}
	export interface PlanFeatureModel
	{
		feature: Enums.SubscriptionFeature;
		isEnabled: boolean;
		monthlyLimit?: number;
		hardLimit?: number;
	}
	export interface SubscriptionLimitErrorModel
	{
		code: string;
		feature: Enums.SubscriptionFeature;
		limit?: number;
		used: number;
		reserved: number;
		resetsAt?: string;
		upgradeAvailable: boolean;
	}
	export interface SubscriptionPlanModel
	{
		id: number;
		code: string;
		name: string;
		description?: string;
		sortOrder: number;
		prices: JsonModels.Subscriptions.SubscriptionPlanPriceModel[];
		features: JsonModels.Subscriptions.PlanFeatureModel[];
	}
	export interface SubscriptionPlanPriceModel
	{
		id: number;
		currency: string;
		amount: number;
		billingInterval: Enums.BillingInterval;
	}
	export interface UsageReservationModel
	{
		id: number;
		feature: Enums.SubscriptionFeature;
		quantity: number;
		status: Enums.UsageReservationStatus;
		expiresAt: string;
	}
}
export namespace JsonModels.ProgramPlans {
	export interface CustomProgramDayRequest
	{
		date: string;
		dayType: Enums.ProgramPlanDayType;
		workoutTemplateId?: number;
		notes?: string;
	}
	export interface MoveProgramDayRequest
	{
		newDate: string;
	}
	export interface ProgramPlanDayModel
	{
		id: number;
		programPlanId: number;
		scheduledDate: string;
		originalScheduledDate?: string;
		dayType: Enums.ProgramPlanDayType;
		status: Enums.ProgramPlanDayStatus;
		workoutTemplateId?: number;
		workoutTemplateName?: string;
		estimatedDurationMinutes?: number;
		exerciseCount: number;
		startedWorkoutId?: number;
		completedWorkoutId?: number;
		notes?: string;
	}
	export interface ProgramPlanModel
	{
		id: number;
		name: string;
		description?: string;
		goal: Enums.TrainingGoal;
		status: Enums.ProgramPlanStatus;
		scheduleType: Enums.ProgramScheduleType;
		startDate: string;
		endDate?: string;
		targetWorkoutsPerWeek: number;
		isAIGenerated: boolean;
		activatedAt?: string;
		completedAt?: string;
		scheduleRules: JsonModels.ProgramPlans.ProgramPlanScheduleRuleModel[];
	}
	export interface ProgramPlanScheduleRuleModel
	{
		id: number;
		dayOfWeek?: Enums.DayOfWeek;
		rotationDayIndex?: number;
		dayType: Enums.ProgramPlanDayType;
		workoutTemplateId?: number;
		workoutTemplateName?: string;
		weekInterval: number;
		orderIndex: number;
		isOptional: boolean;
	}
	export interface ProgramProgressModel
	{
		scheduledWorkouts: number;
		completedWorkouts: number;
		startedWorkouts: number;
		missedWorkouts: number;
		skippedWorkouts: number;
		remainingWorkouts: number;
		completionPercentage?: number;
		adherencePercentage: number;
		currentStreak: number;
	}
	export interface ProgramScheduleRuleRequest
	{
		dayOfWeek?: Enums.DayOfWeek;
		rotationDayIndex?: number;
		dayType: Enums.ProgramPlanDayType;
		workoutTemplateId?: number;
		weekInterval: number;
		orderIndex: number;
		isOptional: boolean;
	}
	export interface ProgramTodayModel
	{
		date: string;
		hasActiveProgram: boolean;
		programId?: number;
		programName?: string;
		today?: JsonModels.ProgramPlans.ProgramPlanDayModel;
		missedWorkout?: JsonModels.ProgramPlans.ProgramPlanDayModel;
		nextWorkout?: JsonModels.ProgramPlans.ProgramPlanDayModel;
	}
	export interface SaveProgramPlanRequest
	{
		name: string;
		description?: string;
		goal: Enums.TrainingGoal;
		scheduleType: Enums.ProgramScheduleType;
		startDate: string;
		endDate?: string;
		targetWorkoutsPerWeek: number;
		scheduleRules: JsonModels.ProgramPlans.ProgramScheduleRuleRequest[];
		customDays: JsonModels.ProgramPlans.CustomProgramDayRequest[];
	}
}
export namespace JsonModels.MuscleGroups {
	export interface CreateMuscleGroupRequest
	{
		name: string;
		imageUrl?: string;
	}
	export interface MuscleGroupModel
	{
		id: number;
		name: string;
		imageUrl?: string;
	}
	export interface MuscleGroupQueryRequest extends JsonModels.Common.PagedRequest
	{
		search?: string;
	}
}
export namespace JsonModels.Exercises {
	export interface ConfirmImageUploadRequest
	{
		blobName: string;
	}
	export interface CreateAdminExerciseRequest
	{
		name: string;
		description?: string;
		videoUrl?: string;
		primaryMuscleGroupId: number;
		secondaryMuscleGroupId?: number;
		equipment?: Enums.ExerciseEquipment;
		movementPattern?: Enums.ExerciseMovementPattern;
		difficulty?: Enums.ExerciseDifficulty;
		category?: Enums.ExerciseCategory;
		aliases?: string[];
		isPrivate: boolean;
	}
	export interface CreateExerciseRequest
	{
		name: string;
		slug: string;
		description?: string;
		imageUrl?: string;
		videoUrl?: string;
		primaryMuscleGroupId: number;
		secondaryMuscleGroupId?: number;
		equipment?: Enums.ExerciseEquipment;
		movementPattern?: Enums.ExerciseMovementPattern;
		difficulty?: Enums.ExerciseDifficulty;
		category?: Enums.ExerciseCategory;
		aliases?: string[];
		isPublic: boolean;
	}
	export interface ExerciseLookupModel
	{
		id: number;
		userId?: number;
		isGlobal: boolean;
		isPublic: boolean;
		name: string;
		slug: string;
		description?: string;
		imageUrl?: string;
		videoUrl?: string;
		primaryMuscleGroupId: number;
		primaryMuscleGroupName: string;
		secondaryMuscleGroupId?: number;
		secondaryMuscleGroupName?: string;
		equipment?: Enums.ExerciseEquipment;
		movementPattern?: Enums.ExerciseMovementPattern;
		difficulty?: Enums.ExerciseDifficulty;
		category?: Enums.ExerciseCategory;
		aliases: string[];
		creatorUserId?: number;
		creatorDisplayName?: string;
		dateCreated: string;
	}
	export interface ExerciseLookupRequest extends JsonModels.Common.OffsetPagedRequest
	{
		search?: string;
		muscleGroupIds?: number[];
	}
	export interface ExerciseModel
	{
		id: number;
		userId?: number;
		isPublic: boolean;
		name: string;
		slug: string;
		description?: string;
		imageUrl?: string;
		videoUrl?: string;
		primaryMuscleGroupId: number;
		secondaryMuscleGroupId?: number;
		equipment?: Enums.ExerciseEquipment;
		movementPattern?: Enums.ExerciseMovementPattern;
		difficulty?: Enums.ExerciseDifficulty;
		category?: Enums.ExerciseCategory;
		aliases: string[];
		creatorDisplayName?: string;
		dateCreated: string;
		dateModified?: string;
	}
	export interface ExerciseQueryRequest extends JsonModels.Common.PagedRequest
	{
		search?: string;
		isGlobal?: boolean;
		userId?: number;
	}
	export interface ImageUploadTicketModel
	{
		uploadUrl: string;
		blobName: string;
	}
	export interface ImageUploadTicketRequest
	{
		fileName: string;
		contentType: string;
	}
}
export namespace JsonModels.Errors {
	export interface ErrorModel
	{
		id: number;
		source?: string;
		action?: string;
		requestUrl: string;
		userAgent?: string;
		message: string;
		exception?: string;
		dateCreated: string;
		createdById?: number;
		createdByEmail?: string;
	}
	export interface ErrorQueryRequest extends JsonModels.Common.PagedRequest
	{
		search?: string;
	}
}
export namespace JsonModels.Common {
	export interface OffsetPagedRequest
	{
		skip: number;
		take: number;
	}
	export interface PagedRequest
	{
		page: number;
		pageSize: number;
	}
	export interface PagedResponse<T>
	{
		items: T[];
		totalCount: number;
		page: number;
		pageSize: number;
	}
}
export namespace JsonModels.BodyMetrics {
	export interface BodyMetricEntryModel
	{
		id: number;
		bodyWeightKg?: number;
		bodyFatPercentage?: number;
		notes?: string;
		loggedAt: string;
	}
	export interface LogBodyMetricRequest
	{
		bodyWeightKg: number;
		bodyFatPercentage?: number;
		notes?: string;
	}
}
export namespace JsonModels.Auth {
	export interface AuthResponse
	{
		success: boolean;
		message?: string;
		user?: JsonModels.Auth.UserModel;
	}
	export interface ChangePasswordRequest
	{
		currentPassword: string;
		newPassword: string;
	}
	export interface CookieConsentRequest
	{
		analytics: boolean;
		marketing: boolean;
	}
	export interface ForgotPasswordRequest
	{
		email: string;
	}
	export interface GoogleLoginRequest
	{
		credential: string;
	}
	export interface LoginRequest
	{
		email: string;
		password: string;
	}
	export interface RegisterRequest
	{
		email: string;
		password: string;
		firstName: string;
		lastName: string;
	}
	export interface ResetPasswordRequest
	{
		email: string;
		token: string;
		newPassword: string;
	}
	export interface UpdateProfileRequest
	{
		firstName: string;
		lastName?: string;
	}
	export interface UserModel
	{
		id: number;
		email: string;
		firstName?: string;
		lastName?: string;
		roles: Enums.UserRole[];
		cookieConsentAnalytics?: boolean;
		cookieConsentMarketing?: boolean;
		cookieConsentAt?: string;
	}
}
export namespace JsonModels.Analytics {
	export interface AnalyticsOverviewModel
	{
		workoutCount: number;
		totalVolumeKg: number;
		totalSets: number;
		totalReps: number;
		volumeTrend: JsonModels.Analytics.VolumeTrendPointModel[];
		muscleGroupVolumes: JsonModels.Analytics.MuscleGroupVolumeModel[];
		personalRecords: JsonModels.Analytics.PersonalRecordSummaryModel[];
	}
	export interface AnalyticsQueryRequest
	{
		from?: string;
		to?: string;
	}
	export interface ExerciseProgressionModel
	{
		exerciseId: number;
		exerciseName: string;
		points: JsonModels.Analytics.ExerciseProgressionPointModel[];
	}
	export interface ExerciseProgressionPointModel
	{
		date: string;
		bestWeightKg?: number;
		bestReps?: number;
		estimatedOneRepMax?: number;
		totalVolumeKg: number;
	}
	export interface MuscleGroupVolumeModel
	{
		muscleGroupId: number;
		muscleGroupName: string;
		totalVolumeKg: number;
		setCount: number;
	}
	export interface PersonalRecordSummaryModel
	{
		exerciseId: number;
		exerciseName: string;
		primaryMuscleGroupId: number;
		primaryMuscleGroupName: string;
		bestWeightKg?: number;
		bestReps?: number;
		bestEstimatedOneRepMax?: number;
		bestVolumeKg?: number;
		lastTrainedOn: string;
	}
	export interface VolumeTrendPointModel
	{
		periodStart: string;
		totalVolumeKg: number;
		workoutCount: number;
	}
}
export namespace JsonModels.AI {
	export interface AIConversationModel
	{
		id: number;
		title?: string;
		status: Enums.AIConversationStatus;
		lastMessageAt: string;
		messages: JsonModels.AI.AIMessageModel[];
	}
	export interface AIConversationSummaryModel
	{
		id: number;
		title?: string;
		status: Enums.AIConversationStatus;
		lastMessageAt: string;
		messageCount: number;
	}
	export interface AIMessageModel
	{
		id: number;
		role: Enums.AIMessageRole;
		content: string;
		toolName?: string;
		dateCreated: string;
	}
	export interface AIUsageSummaryModel
	{
		feature: string;
		used: number;
		limit?: number;
		remaining?: number;
	}
	export interface CreateAIConversationRequest
	{
		title?: string;
	}
	export interface SendAIMessageRequest
	{
		content: string;
	}
	export interface SendAIMessageResponse
	{
		conversationId: number;
		message: JsonModels.AI.AIMessageModel;
		usedTools: string[];
		actions: JsonModels.AIActions.AIActionModel[];
		usage: JsonModels.AI.AIUsageSummaryModel;
	}
}
export namespace JsonModels.AIActions {
	export interface AIActionModel
	{
		id: number;
		conversationId: number;
		actionType: Enums.AIActionType;
		status: Enums.AIActionStatus;
		preview: JsonModels.AIActions.AIActionPreviewModel;
		validationSummary: JsonModels.AIActions.AIActionValidationSummaryModel;
		result?: JsonModels.AIActions.AIActionResultModel;
		expiresAt?: string;
		executedAt?: string;
		failureReason?: string;
		dateCreated: string;
	}
	export interface AIActionPreviewModel
	{
		title: string;
		subtitle?: string;
		lines: JsonModels.AIActions.AIActionPreviewLineModel[];
	}
	export interface AIActionPreviewLineModel
	{
		label: string;
		value: string;
	}
	export interface AIActionResultModel
	{
		createdEntityId: number;
		createdEntityName?: string;
		entityKind?: string;
	}
	export interface AIActionValidationSummaryModel
	{
		warnings: string[];
		errors: string[];
		duplicateCandidates: JsonModels.AIActions.DuplicateCandidateModel[];
	}
	export interface DuplicateCandidateModel
	{
		id: number;
		name: string;
		reason?: string;
	}
	export interface ProposeExercisePayload
	{
		name: string;
		description?: string;
		primaryMuscleGroupId: number;
		secondaryMuscleGroupId?: number;
		equipment?: Enums.ExerciseEquipment;
		movementPattern?: Enums.ExerciseMovementPattern;
		difficulty?: Enums.ExerciseDifficulty;
		category?: Enums.ExerciseCategory;
		isPublic: boolean;
		aliases: string[];
		isGlobal: boolean;
	}
	export interface ProposeWorkoutPayload
	{
		title: string;
		notes?: string;
		exercises: JsonModels.AIActions.ProposedExercise[];
		newExercises: JsonModels.AIActions.ProposedNewExercise[];
	}
	export interface ProposeWorkoutTemplatePayload
	{
		name: string;
		description?: string;
		estimatedDurationMinutes?: number;
		isPublic: boolean;
		exercises: JsonModels.AIActions.ProposedExercise[];
		newExercises: JsonModels.AIActions.ProposedNewExercise[];
	}
	export interface ProposedNewExercise extends JsonModels.AIActions.ProposeExercisePayload
	{
		clientKey: string;
	}
	export interface ProposedExercise
	{
		exerciseId: number;
		newExerciseClientKey?: string;
		sets: JsonModels.AIActions.ProposedSet[];
	}
	export interface ProposedSet
	{
		setType: Enums.ExerciseSetType;
		reps?: number;
		weightKg?: number;
		rpe?: number;
		restSeconds?: number;
	}
	export interface ProposeProgramPlanPayload
	{
		name: string;
		description?: string;
		goal: Enums.TrainingGoal;
		scheduleType: Enums.ProgramScheduleType;
		startDate: string;
		endDate?: string;
		workoutsPerWeek: number;
		schedule: JsonModels.AIActions.ProposedProgramScheduleItem[];
		newTemplates: JsonModels.AIActions.ProposedProgramTemplate[];
	}
	export interface ProposedProgramScheduleItem
	{
		dayOfWeek?: Enums.DayOfWeek;
		rotationDayIndex?: number;
		dayType: Enums.ProgramPlanDayType;
		existingWorkoutTemplateId?: number;
		newWorkoutTemplateClientKey?: string;
		isOptional: boolean;
	}
	export interface ProposedProgramTemplate
	{
		clientKey: string;
		name: string;
		description?: string;
		estimatedDurationMinutes?: number;
		exercises: JsonModels.AIActions.ProposedExercise[];
	}
	export interface ProposeProgramUpdatePayload
	{
		programPlanId: number;
		reason: string;
		workoutsPerWeek: number;
		schedule: JsonModels.AIActions.ProposedProgramScheduleItem[];
		newTemplates: JsonModels.AIActions.ProposedProgramTemplate[];
	}
}
export namespace JsonModels.AdminSubscriptions {
	export interface AssignPlanOverrideRequest
	{
		planCode: string;
		reason: string;
		endsAt?: string;
	}
	export interface SavePlanRequest
	{
		code: string;
		name: string;
		description?: string;
		isActive: boolean;
		isPublic: boolean;
		sortOrder: number;
		prices: JsonModels.AdminSubscriptions.PlanPriceRequest[];
		entitlements: JsonModels.AdminSubscriptions.PlanEntitlementRequest[];
	}
	export interface PlanPriceRequest
	{
		currency: string;
		amount: number;
		billingInterval: Enums.BillingInterval;
		stripePriceId: string;
		isActive: boolean;
	}
	export interface PlanEntitlementRequest
	{
		feature: Enums.SubscriptionFeature;
		isEnabled: boolean;
		dailyLimit?: number;
		monthlyLimit?: number;
		maximumPerRequest?: number;
		softLimit?: number;
		hardLimit?: number;
	}
	export interface SubscriptionPlanAdminModel
	{
		id: number;
		code: string;
		name: string;
		description?: string;
		isActive: boolean;
		isPublic: boolean;
		sortOrder: number;
		subscriberCount: number;
		prices: JsonModels.AdminSubscriptions.PlanPriceAdminModel[];
		entitlements: JsonModels.AdminSubscriptions.PlanEntitlementAdminModel[];
	}
	export interface PlanPriceAdminModel
	{
		id: number;
		currency: string;
		amount: number;
		billingInterval: Enums.BillingInterval;
		stripePriceId: string;
		isActive: boolean;
	}
	export interface PlanEntitlementAdminModel
	{
		id: number;
		feature: Enums.SubscriptionFeature;
		isEnabled: boolean;
		dailyLimit?: number;
		monthlyLimit?: number;
		maximumPerRequest?: number;
		softLimit?: number;
		hardLimit?: number;
	}
	export interface SubscriptionQueryRequest extends JsonModels.Common.PagedRequest
	{
		search?: string;
		planCode?: string;
		status?: Enums.SubscriptionStatus;
		overriddenOnly: boolean;
	}
	export interface UsageQueryRequest extends JsonModels.Common.PagedRequest
	{
		search?: string;
		userId?: number;
		feature?: Enums.SubscriptionFeature;
		periodStart?: string;
		atLimitOnly: boolean;
	}
	export interface UserSubscriptionAdminModel
	{
		userId: number;
		email?: string;
		fullName?: string;
		effectivePlanCode: string;
		effectivePlanName: string;
		source: Enums.EntitlementSource;
		subscriptionId?: number;
		subscriptionStatus?: Enums.SubscriptionStatus;
		currentPeriodEnd?: string;
		cancelAtPeriodEnd: boolean;
		activeOverride?: JsonModels.AdminSubscriptions.PlanOverrideAdminModel;
	}
	export interface PlanOverrideAdminModel
	{
		id: number;
		planCode: string;
		reason: string;
		createdByUserId: number;
		startsAt: string;
		endsAt?: string;
	}
	export interface UserUsageAdminModel
	{
		id: number;
		userId: number;
		email?: string;
		feature: Enums.SubscriptionFeature;
		periodStart: string;
		periodEnd: string;
		used: number;
		reserved: number;
		effectiveLimit?: number;
	}
}
export namespace JsonModels.AdminAI {
	export interface AIAdminOverviewModel
	{
		days: number;
		from: string;
		to: string;
		totalRuns: number;
		failedRuns: number;
		activeUsers: number;
		conversations: number;
		messages: number;
		toolCalls: number;
		failedToolCalls: number;
		proposedActions: number;
		confirmedActions: number;
		inputTokens: number;
		outputTokens: number;
		estimatedCost: number;
		averageDurationMilliseconds: number;
		p95DurationMilliseconds: number;
		topTools: JsonModels.AdminAI.AIToolUsageModel[];
		topUsersByCost: JsonModels.AdminAI.AIUserCostModel[];
		costByDay: JsonModels.AdminAI.AICostByDayModel[];
		topUnsupportedCategories: JsonModels.AdminAI.UnsupportedCategoryCountModel[];
	}
	export interface AIToolUsageModel
	{
		toolName: string;
		callCount: number;
		failureCount: number;
		averageDurationMilliseconds: number;
	}
	export interface AIUserCostModel
	{
		userId: number;
		email?: string;
		runCount: number;
		estimatedCost: number;
	}
	export interface AICostByDayModel
	{
		date: string;
		runCount: number;
		estimatedCost: number;
	}
	export interface UnsupportedCategoryCountModel
	{
		category: string;
		groupCount: number;
		occurrenceCount: number;
	}
	export interface AIAdminRunModel
	{
		id: number;
		userId: number;
		userEmail?: string;
		conversationId: number;
		status: Enums.AIRunStatus;
		provider: string;
		model: string;
		promptVersion: string;
		inputTokens: number;
		outputTokens: number;
		cachedInputTokens: number;
		estimatedCost?: number;
		toolCallCount: number;
		durationMilliseconds: number;
		errorCode?: string;
		errorMessage?: string;
		startedAt: string;
		completedAt?: string;
		toolExecutions: JsonModels.AdminAI.AIAdminToolExecutionModel[];
	}
	export interface AIAdminToolExecutionModel
	{
		id: number;
		toolName: string;
		status: Enums.AIToolExecutionStatus;
		durationMilliseconds: number;
		errorCode?: string;
		errorMessage?: string;
		startedAt: string;
	}
	export interface AIAdminUsageSummaryModel
	{
		period: string;
		features: JsonModels.AdminAI.AIAdminFeatureUsageModel[];
	}
	export interface AIAdminFeatureUsageModel
	{
		feature: Enums.SubscriptionFeature;
		userCount: number;
		usedTotal: number;
		atOrOverLimitCount: number;
	}
	export interface AIConversationDetailModel
	{
		id: number;
		userId: number;
		userEmail?: string;
		title?: string;
		status: Enums.AIConversationStatus;
		lastMessageAt: string;
		dateCreated: string;
		contentVisible: boolean;
		messages: JsonModels.AdminAI.AIAdminMessageModel[];
		runs: JsonModels.AdminAI.AIAdminRunModel[];
		actions: JsonModels.AdminAI.AIAdminActionModel[];
	}
	export interface AIAdminMessageModel
	{
		id: number;
		role: Enums.AIMessageRole;
		content: string;
		toolName?: string;
		dateCreated: string;
	}
	export interface AIAdminActionModel
	{
		id: number;
		actionType: Enums.AIActionType;
		status: Enums.AIActionStatus;
		dateCreated: string;
		executedAt?: string;
		failureReason?: string;
	}
	export interface AIConversationListItemModel
	{
		id: number;
		userId: number;
		userEmail?: string;
		title?: string;
		status: Enums.AIConversationStatus;
		messageCount: number;
		runCount: number;
		estimatedCost: number;
		lastMessageAt: string;
		dateCreated: string;
	}
	export interface AIConversationQueryRequest extends JsonModels.Common.PagedRequest
	{
		search?: string;
		userId?: number;
		status?: Enums.AIConversationStatus;
		from?: string;
		to?: string;
	}
	export interface AICostSummaryModel
	{
		from: string;
		to: string;
		estimatedCost: number;
		inputTokens: number;
		outputTokens: number;
		cachedInputTokens: number;
		byDay: JsonModels.AdminAI.AICostByDayModel[];
		byModel: JsonModels.AdminAI.AICostByModelModel[];
		byPlan: JsonModels.AdminAI.AICostByPlanModel[];
	}
	export interface AICostByModelModel
	{
		model: string;
		runCount: number;
		estimatedCost: number;
	}
	export interface AICostByPlanModel
	{
		planCode: string;
		runCount: number;
		estimatedCost: number;
	}
	export interface AIRunQueryRequest extends JsonModels.Common.PagedRequest
	{
		userId?: number;
		conversationId?: number;
		status?: Enums.AIRunStatus;
		model?: string;
		from?: string;
		to?: string;
		failuresOnly: boolean;
	}
	export interface AISettingsModel
	{
		provider: string;
		defaultModel: string;
		fastModel: string;
		reasoningModel: string;
		visionModel: string;
		imageModel: string;
		timeoutSeconds: number;
		maximumToolIterations: number;
		maximumToolCallsPerRun: number;
		maximumConversationMessages: number;
		maximumContextTokens: number;
		maximumOutputTokens: number;
		maximumMessageCharacters: number;
		storeRawProviderPayload: boolean;
		conversationRetentionDays: number;
		operationalLogRetentionDays: number;
		temporaryUploadRetentionHours: number;
		expiredActionRetentionDays: number;
		isStored: boolean;
	}
	export interface SaveAISettingsRequest
	{
		defaultModel: string;
		fastModel: string;
		reasoningModel: string;
		visionModel: string;
		imageModel: string;
		timeoutSeconds: number;
		maximumToolIterations: number;
		maximumToolCallsPerRun: number;
		maximumConversationMessages: number;
		maximumContextTokens: number;
		maximumOutputTokens: number;
		maximumMessageCharacters: number;
		storeRawProviderPayload: boolean;
		conversationRetentionDays: number;
		operationalLogRetentionDays: number;
		temporaryUploadRetentionHours: number;
		expiredActionRetentionDays: number;
	}
	export interface AIUserCostBreakdownModel
	{
		userId: number;
		email?: string;
		planCode: string;
		planName: string;
		runCount: number;
		inputTokens: number;
		cachedInputTokens: number;
		outputTokens: number;
		totalTokens: number;
		estimatedCost: number;
		byModel: JsonModels.AdminAI.AIUserModelCostModel[];
	}
	export interface AIUserModelCostModel
	{
		model: string;
		runCount: number;
		inputTokens: number;
		cachedInputTokens: number;
		outputTokens: number;
		estimatedCost: number;
	}
	export interface AIUserCostQueryRequest extends JsonModels.Common.PagedRequest
	{
		days: number;
		search?: string;
	}
	export interface RecordUnsupportedRequestRequest
	{
		category: string;
		requestedFunctionality: string;
		userIntentSummary?: string;
		suggestedFallback?: string;
		conversationId: number;
		messageId?: number;
	}
	export interface UnsupportedAIRequestModel
	{
		id: number;
		category: string;
		normalizedKey: string;
		requestedFunctionality: string;
		userIntentSummary?: string;
		suggestedFallback?: string;
		status: Enums.UnsupportedRequestStatus;
		occurrenceCount: number;
		distinctUserCount: number;
		firstRequestedAt: string;
		lastRequestedAt: string;
		adminNotes?: string;
		externalTrackingUrl?: string;
		externalTrackingKey?: string;
		recentOccurrences: JsonModels.AdminAI.UnsupportedRequestOccurrenceModel[];
	}
	export interface UnsupportedRequestOccurrenceModel
	{
		id: number;
		userId: number;
		userEmail?: string;
		conversationId: number;
		reportedAt: string;
	}
	export interface UnsupportedRequestQueryRequest extends JsonModels.Common.PagedRequest
	{
		search?: string;
		category?: string;
		status?: Enums.UnsupportedRequestStatus;
	}
	export interface UpdateUnsupportedRequestRequest
	{
		status: Enums.UnsupportedRequestStatus;
		adminNotes?: string;
		externalTrackingUrl?: string;
		externalTrackingKey?: string;
	}
}
export interface JsonData<T>
{
	success: boolean;
	data?: T;
	error?: string;
	warning?: string;
}
