//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export namespace Enums {
	export enum UserRole {
		User = 1,
		Admin = 2
	}
}
export namespace JsonModels.MuscleGroups {
	export interface CreateMuscleGroupRequest
	{
		name: string;
		imageUrl?: string;
	}
	export interface MuscleGroupModel
	{
		id: number;
		name: string;
		imageUrl?: string;
	}
	export interface MuscleGroupQueryRequest extends JsonModels.Common.PagedRequest
	{
		search?: string;
	}
}
export namespace JsonModels.Exercises {
	export interface CreateExerciseRequest
	{
		name: string;
		slug: string;
		description?: string;
		imageUrl?: string;
		videoUrl?: string;
		primaryMuscleGroupId: number;
		secondaryMuscleGroupId?: number;
	}
	export interface ExerciseModel
	{
		id: number;
		userId?: number;
		name: string;
		slug: string;
		description?: string;
		imageUrl?: string;
		videoUrl?: string;
		primaryMuscleGroupId: number;
		secondaryMuscleGroupId?: number;
		dateCreated: string;
		dateModified?: string;
	}
	export interface ExerciseQueryRequest extends JsonModels.Common.PagedRequest
	{
		search?: string;
		isGlobal?: boolean;
		userId?: number;
	}
}
export namespace JsonModels.Common {
	export interface PagedRequest
	{
		page: number;
		pageSize: number;
	}
	export interface PagedResponse<T>
	{
		items: T[];
		totalCount: number;
		page: number;
		pageSize: number;
	}
}
export namespace JsonModels.Auth {
	export interface AuthResponse
	{
		success: boolean;
		message?: string;
		user?: JsonModels.Auth.UserModel;
	}
	export interface LoginRequest
	{
		email: string;
		password: string;
	}
	export interface RegisterRequest
	{
		email: string;
		password: string;
		firstName: string;
		lastName: string;
	}
	export interface UpdateProfileRequest
	{
		firstName: string;
		lastName?: string;
	}
	export interface UserModel
	{
		id: number;
		email: string;
		firstName?: string;
		lastName?: string;
		roles: Enums.UserRole[];
	}
}
export interface JsonData<T>
{
	success: boolean;
	data?: T;
	error?: string;
	warning?: string;
}
