export * from "./JsonModels";

import type { JsonModels } from "./backend";

export type AdminUser = JsonModels.Users.AdminUserModel;
export type AnalyticsOverview = JsonModels.Analytics.AnalyticsOverviewModel;
export type BodyMetricEntry = JsonModels.BodyMetrics.BodyMetricEntryModel;
export type Error = JsonModels.Errors.ErrorModel;
export type Exercise = JsonModels.Exercises.ExerciseModel;
export type ExerciseHistory = JsonModels.Workouts.ExerciseHistoryModel;
export type ExerciseHistorySession = JsonModels.Workouts.ExerciseHistorySessionModel;
export type ExerciseLookup = JsonModels.Exercises.ExerciseLookupModel;
export type ExerciseProgression = JsonModels.Analytics.ExerciseProgressionModel;
export type ExerciseProgressionPoint = JsonModels.Analytics.ExerciseProgressionPointModel;
export type ImageUploadTicket = JsonModels.Exercises.ImageUploadTicketModel;
export type MuscleGroup = JsonModels.MuscleGroups.MuscleGroupModel;
export type MuscleGroupVolume = JsonModels.Analytics.MuscleGroupVolumeModel;
export type PersonalRecordSummary = JsonModels.Analytics.PersonalRecordSummaryModel;
export type PreviousExerciseSet = JsonModels.Workouts.PreviousExerciseSetModel;
export type PreviousExerciseSets = JsonModels.Workouts.PreviousExerciseSetsModel;
export type ProgramPlan = JsonModels.ProgramPlans.ProgramPlanModel;
export type ProgramPlanDay = JsonModels.ProgramPlans.ProgramPlanDayModel;
export type ProgramPlanScheduleRule = JsonModels.ProgramPlans.ProgramPlanScheduleRuleModel;
export type ProgramProgress = JsonModels.ProgramPlans.ProgramProgressModel;
export type ProgramToday = JsonModels.ProgramPlans.ProgramTodayModel;
export type TrainingProfile = JsonModels.TrainingProfiles.TrainingProfileModel;
export type User = JsonModels.Auth.UserModel;
export type VolumeTrendPoint = JsonModels.Analytics.VolumeTrendPointModel;
export type Workout = JsonModels.Workouts.WorkoutModel;
export type WorkoutCalendarDay = JsonModels.Workouts.WorkoutCalendarDayModel;
export type WorkoutCreated = JsonModels.Workouts.WorkoutCreatedModel;
export type WorkoutExercise = JsonModels.Workouts.WorkoutExerciseModel;
export type WorkoutExerciseGroup = JsonModels.Workouts.WorkoutExerciseGroupModel;
export type WorkoutSet = JsonModels.Workouts.WorkoutSetModel;
export type WorkoutTemplate = JsonModels.WorkoutTemplates.WorkoutTemplateModel;
export type WorkoutTemplateExercise = JsonModels.WorkoutTemplates.WorkoutTemplateExerciseModel;
export type WorkoutTemplateExerciseGroup = JsonModels.WorkoutTemplates.WorkoutTemplateExerciseGroupModel;
export type WorkoutTemplateExerciseSet = JsonModels.WorkoutTemplates.WorkoutTemplateExerciseSetModel;
